<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Devlooped</RootNamespace>
    <AssemblyName>md</AssemblyName>
    <NoWarn>CS9107</NoWarn>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Description>Minimal markdown build/test output for AI consumption.</Description>

    <PackageId>md</PackageId>
    <ToolCommandName>dotnet-md</ToolCommandName>
    <PackAsTool>true</PackAsTool>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageTags>dotnet dotnet-tool</PackageTags>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageLicenseFile>OSMFEULA.txt</PackageLicenseFile>

    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.2" />
    <PackageReference Include="Devlooped.Web" Version="1.4.0" />
    <PackageReference Include="MSBuild.StructuredLogger" Version="2.3.213" />
    <PackageReference Include="NuGet.Frameworks" Version="7.6.0" />
    <PackageReference Include="NuGetizer" Version="1.4.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.CommandLine" Version="2.0.9" />
    <PackageReference Include="ThisAssembly.Project" Version="2.1.2" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tests" />
    <ProjectProperty Include="ToolCommandName" />
    <ProjectProperty Include="PackageId" />
    <ProjectProperty Include="PackageProjectUrl" />
    <None Include="..\..\osmfeula.txt" Link="osmfeula.txt" Pack="true" PackagePath="OSMFEULA.txt" />
    <None Include="icon.png" Pack="true" PackagePath="icon.png" />
    <None Include="readme.md" Pack="true" PackagePath="readme.md" />
  </ItemGroup>
</Project>